let pets = [
    {
        name: "Baxter",
        image: "images/Labrador_Retriever.webp",
        type: "Dog",
        breed: "Beagle",
        sex: "Male",
        color: "Tri-color (Black Brown White)",
        spayedNeutered: "Yes",
        age: "5 Years",
        animalID: "34621",
        microchipNumber: "982000364789210",
        status: ["Health checked", "Vaccinations up to date", "Regularly dewormed", "Microchipped"],
        about: "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter wasrescued from a shelter and has blossomed into a friendly and outgoing boy. Heloves long walks and has a keen sense of smell. He's great with kids and otherdogs, making him the perfect family pet. His favorite pastime is chasing squirrelsin the park and curling up for naps. Baxter is looking for a loving home where hecan share his endless affection and playful spirit."
    },
    {
        name: "Luna",
        image: "images/Labrador_Retriever.webp",
        type: "Cat",
        breed: "Maine Coon",
        sex: "Female",
        color: "Grey with white markings",
        spayedNeutered: "Yes",
        age: "3 Years",
        animalId: "57281",
        microchipNumber: "981120019776432",
        status: [],
        about: "Luna is a majestic Maine Coon with a fluffy grey coat and striking white markings.She was found as a stray and has since become a gentle and affectionatecompanion. Luna enjoys perching on windowsills, watching birds, and being thecenter of attention. She's a bit shy at first but warms up quickly, especially if youhave treats! Luna would thrive in a calm environment where she can relax and bepampered like the queen she is."
    },
    {
        name: "Sandy",
        image: "images/Labrador_Retriever.webp",

        type: "Dog",
        breed: "Golden Retriever",
        sex: "Female",
        color: "Golden",
        spayedNeutered: "Yes",
        age: "7 Years",
        animalId: "41382",
        microchipNumber: "985112004567890",
        status: [],
        about: "Sandy is a heartwarming Golden Retriever with a golden coat as bright as herpersonality. Rescued from a neglectful situation, she has shown incredibleresilience and love for life. Sandy is great with children and other pets, makingher an ideal family dog. She enjoys outdoor adventures, especially swimming andfetching. Sandy is looking for a forever home where she can spread her joy andlove."
    },
    {
        name: "Baxter",
        image: "images/Labrador_Retriever.webp",
        type: "Dog",
        breed: "Beagle",
        sex: "Male",
        color: "Tri-color (Black Brown White)",
        spayedNeutered: "Yes",
        age: "5 Years",
        animalID: "34621",
        microchipNumber: "982000364789210",
        status: ["Health checked", "Vaccinations up to date", "Regularly dewormed", "Microchipped"],
        about: "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter wasrescued from a shelter and has blossomed into a friendly and outgoing boy. Heloves long walks and has a keen sense of smell. He's great with kids and otherdogs, making him the perfect family pet. His favorite pastime is chasing squirrelsin the park and curling up for naps. Baxter is looking for a loving home where hecan share his endless affection and playful spirit."
    },
    {
        name: "Luna",
        image: "images/Labrador_Retriever.webp",
        type: "Cat",
        breed: "Maine Coon",
        sex: "Female",
        color: "Grey with white markings",
        spayedNeutered: "Yes",
        age: "3 Years",
        animalId: "57281",
        microchipNumber: "981120019776432",
        status: [],
        about: "Luna is a majestic Maine Coon with a fluffy grey coat and striking white markings.She was found as a stray and has since become a gentle and affectionatecompanion. Luna enjoys perching on windowsills, watching birds, and being thecenter of attention. She's a bit shy at first but warms up quickly, especially if youhave treats! Luna would thrive in a calm environment where she can relax and bepampered like the queen she is."
    },
    {
        name: "Sandy",
        image: "images/Labrador_Retriever.webp",

        type: "Dog",
        breed: "Golden Retriever",
        sex: "Female",
        color: "Golden",
        spayedNeutered: "Yes",
        age: "7 Years",
        animalId: "41382",
        microchipNumber: "985112004567890",
        status: [],
        about: "Sandy is a heartwarming Golden Retriever with a golden coat as bright as herpersonality. Rescued from a neglectful situation, she has shown incredibleresilience and love for life. Sandy is great with children and other pets, makingher an ideal family dog. She enjoys outdoor adventures, especially swimming andfetching. Sandy is looking for a forever home where she can spread her joy andlove."
    },{
        name: "Baxter",
        image: "images/Labrador_Retriever.webp",
        type: "Dog",
        breed: "Beagle",
        sex: "Male",
        color: "Tri-color (Black Brown White)",
        spayedNeutered: "Yes",
        age: "5 Years",
        animalID: "34621",
        microchipNumber: "982000364789210",
        status: ["Health checked", "Vaccinations up to date", "Regularly dewormed", "Microchipped"],
        about: "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter wasrescued from a shelter and has blossomed into a friendly and outgoing boy. Heloves long walks and has a keen sense of smell. He's great with kids and otherdogs, making him the perfect family pet. His favorite pastime is chasing squirrelsin the park and curling up for naps. Baxter is looking for a loving home where hecan share his endless affection and playful spirit."
    },
    {
        name: "Luna",
        image: "images/Labrador_Retriever.webp",
        type: "Cat",
        breed: "Maine Coon",
        sex: "Female",
        color: "Grey with white markings",
        spayedNeutered: "Yes",
        age: "3 Years",
        animalId: "57281",
        microchipNumber: "981120019776432",
        status: [],
        about: "Luna is a majestic Maine Coon with a fluffy grey coat and striking white markings.She was found as a stray and has since become a gentle and affectionatecompanion. Luna enjoys perching on windowsills, watching birds, and being thecenter of attention. She's a bit shy at first but warms up quickly, especially if youhave treats! Luna would thrive in a calm environment where she can relax and bepampered like the queen she is."
    },
    {
        name: "Sandy",
        image: "images/Labrador_Retriever.webp",

        type: "Dog",
        breed: "Golden Retriever",
        sex: "Female",
        color: "Golden",
        spayedNeutered: "Yes",
        age: "7 Years",
        animalId: "41382",
        microchipNumber: "985112004567890",
        status: [],
        about: "Sandy is a heartwarming Golden Retriever with a golden coat as bright as herpersonality. Rescued from a neglectful situation, she has shown incredibleresilience and love for life. Sandy is great with children and other pets, makingher an ideal family dog. She enjoys outdoor adventures, especially swimming andfetching. Sandy is looking for a forever home where she can spread her joy andlove."
    },
];
